Add vendor info to device
truenas/py-SMART pull request #44
Opened 2022-04-12 18:50 UTC by pieterhelsen

Added support for reading the Vendor property from the information section. Below are two snippets from WD and Seagate drives that support this property:

```
=== START OF INFORMATION SECTION ===
Vendor:               Seagate
Product:              ST16000NM001G-2K
```

```
=== START OF INFORMATION SECTION ===
Vendor:               WDC
Product:              WD161KRYZ-01AGBB
```

2022-04-13 09:36 UTC, ralequi approved these changes

2022-04-13 09:39 UTC, ralequi requested changes
It seems it fails in some tests.
Could you check them please? it seems not always split(:)[1] works

2022-04-13 09:43 UTC, ralequi commented
Also, if you can add some device test example that checks the vendor, would be welcomed.
Thanks for your contrib

2022-04-13 15:49 UTC, pieterhelsen commented
Thanks for the feedback. The tests already included some drives with the Vendor attribute, so I updated the `device.json` files to check these values as part of the `pytest` suite. 

All tests are passing with a deprecation warning in https://github.com/truenas/py-SMART/blob/b16af735a03c6133604babf6938c4fb3eaa7667a/pySMART/device_list.py#L105 that I decided not to fix within the scope of this PR.

2022-04-14 16:23 UTC, ralequi approved these changes

2022-04-14 16:23 UTC, merged

2022-04-14 16:24 UTC, ralequi commented
Hi!

Thank you for your contribution. Much appreciated.